In [23]:
import tensorflow as tf
import keras
import random
import gym
print(tf.__version__)   
print(keras.__version__)   

2.12.0
2.12.0


In [24]:
env=gym.make('CartPole-v1')

In [25]:
actions=env.action_space.n
states=env.observation_space.shape[0]
print(actions)
print(states)

2
4


In [26]:
run=True
env.reset()
ic=0
while run:
    
    env.render()
    act=random.randint(0,1)
    n_steate,reward,done,info=env.step(act)
    print(n_steate,reward,done,info)
    ic+=1
    if ic>600:
        ic=0
        run=False
env.close()
    

[-0.03672859 -0.22235063 -0.01669199  0.31908813] 1.0 False {}
[-0.0411756  -0.41723093 -0.01031022  0.60646063] 1.0 False {}
[-0.04952022 -0.61220723  0.00181899  0.8958784 ] 1.0 False {}
[-0.06176436 -0.41710997  0.01973656  0.60376775] 1.0 False {}
[-0.07010657 -0.61250234  0.03181191  0.90260136] 1.0 False {}
[-0.08235661 -0.4178254   0.04986394  0.6200849 ] 1.0 False {}
[-0.09071312 -0.22343403  0.06226564  0.34351417] 1.0 False {}
[-0.0951818  -0.02925061  0.06913592  0.07109778] 1.0 False {}
[-0.09576681  0.16481556  0.07055788 -0.19899629] 1.0 False {}
[-0.0924705  -0.03124091  0.06657795  0.11508349] 1.0 False {}
[-0.09309532  0.16286702  0.06887962 -0.1558739 ] 1.0 False {}
[-0.08983798  0.35693863  0.06576214 -0.4260564 ] 1.0 False {}
[-0.0826992   0.55107045  0.05724102 -0.6973046 ] 1.0 False {}
[-0.0716778   0.74535394  0.04329492 -0.97143275] 1.0 False {}
[-0.05677072  0.5496785   0.02386627 -0.66546994] 1.0 False {}
[-0.04577715  0.74446046  0.01055687 -0.9505437 ] 1.0 F

In [27]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense,Flatten
from keras.optimizers import Adam


In [28]:
modelq=Sequential()
modelq.add(Flatten(input_shape=(1,4)))
modelq.add(Dense(48,activation='relu'))
modelq.add(Dense(24,activation='relu'))
modelq.add(Dense(2,activation='linear'))
modelq.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_3 (Flatten)         (None, 4)                 0         
                                                                 
 dense_9 (Dense)             (None, 48)                240       
                                                                 
 dense_10 (Dense)            (None, 24)                1176      
                                                                 
 dense_11 (Dense)            (None, 2)                 50        
                                                                 
Total params: 1,466
Trainable params: 1,466
Non-trainable params: 0
_________________________________________________________________


In [29]:
from rl.agents import DQNAgent
from rl.memory import SequentialMemory
from rl.policy import BoltzmannQPolicy

In [30]:
policy=BoltzmannQPolicy()
memory=SequentialMemory(limit=50000,window_length=1)
robot=DQNAgent(model=modelq, policy=policy,memory=memory,nb_actions=2
               ,nb_steps_warmup=10,target_model_update=1e-2)
robot.compile(Adam(lr=1e-3),metrics=['mae'])

In [31]:
robot.fit(env=env,nb_steps=50000,visualize=False,verbose=True)


Training for 50000 steps ...
Interval 1 (0 steps performed)
    1/10000 [..............................] - ETA: 5:59 - reward: 1.0000

C:\Users\EMTOO\AppData\Roaming\Python\Python38\site-packages\keras\engine\training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,
C:\Users\EMTOO\AppData\Roaming\Python\Python38\site-packages\rl\memory.py:37: UserWarning: Not enough entries to sample without replacement. Consider increasing your warm-up phase to avoid oversampling!
  warnings.warn('Not enough entries to sample without replacement. Consider increasing your warm-up phase to avoid oversampling!')
C:\Users\EMTOO\AppData\Roaming\Python\Python38\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)


   60/10000 [..............................] - ETA: 1:12 - reward: 1.0000

C:\Users\EMTOO\AppData\Roaming\Python\Python38\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 11 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
C:\Users\EMTOO\AppData\Roaming\Python\Python38\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 12 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
C:\Users\EMTOO\AppData\Roaming\Python\Python38\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 13 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
C:\Users\EMTOO\AppData\Roaming\Python\Python38\site-packages\rl\memory.py:38: DeprecationWarning: This function is deprecated. Please call randint(1, 14 + 1) instead
  batch_idxs = np.random.random_integers(low, high - 1, size=size)
C:\Users\EMTOO\AppData\Roaming\Python\Python38\site-packages\rl\memo

10000/10000 [==============================] - 30s 3ms/step - reward: 1.0000
94 episodes - episode_reward: 105.798 [11.000, 445.000] - loss: 1.643 - mae: 19.312 - mean_q: 39.262

Interval 2 (10000 steps performed)
10000/10000 [==============================] - 29s 3ms/step - reward: 1.0000
44 episodes - episode_reward: 224.227 [171.000, 362.000] - loss: 2.401 - mae: 41.133 - mean_q: 83.199

Interval 3 (20000 steps performed)
10000/10000 [==============================] - 29s 3ms/step - reward: 1.0000
46 episodes - episode_reward: 218.696 [158.000, 421.000] - loss: 1.605 - mae: 42.749 - mean_q: 86.278

Interval 4 (30000 steps performed)
10000/10000 [==============================] - 29s 3ms/step - reward: 1.0000
41 episodes - episode_reward: 245.390 [157.000, 356.000] - loss: 1.026 - mae: 40.295 - mean_q: 81.197

Interval 5 (40000 steps performed)
10000/10000 [==============================] - 30s 3ms/step - reward: 1.0000
done, took 147.395 seconds


In [32]:
out=robot.test(env,nb_episodes=10,visualize=False)

Testing for 10 episodes ...
Episode 1: reward: 500.000, steps: 500
Episode 2: reward: 500.000, steps: 500
Episode 3: reward: 500.000, steps: 500
Episode 4: reward: 500.000, steps: 500
Episode 5: reward: 500.000, steps: 500
Episode 6: reward: 500.000, steps: 500
Episode 7: reward: 500.000, steps: 500
Episode 8: reward: 500.000, steps: 500
Episode 9: reward: 500.000, steps: 500
Episode 10: reward: 500.000, steps: 500


In [33]:
robot.save_weights('rl.h5')