In [6]:
import tensorflow as tf
import keras
import random
import gym
print(tf.__version__)   
print(keras.__version__)   

2.12.0
2.12.0


In [7]:
env=gym.make('CartPole-v1')

C:\Users\EMTOO\AppData\Roaming\Python\Python38\site-packages\gym\core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
C:\Users\EMTOO\AppData\Roaming\Python\Python38\site-packages\gym\wrappers\step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [8]:
actions=env.action_space.n
states=env.observation_space.shape[0]
print(actions)
print(states)

2
4


In [9]:
run=True
env.reset()
ic=0
while run:
    
    env.render()
    act=random.randint(0,1)
    n_steate,reward,done,info=env.step(act)
    print(n_steate,reward,done,info)
    ic+=1
    if ic>600:
        ic=0
        run=False
env.close()
    

[ 0.01727824  0.20155306 -0.02327432 -0.31591022] 1.0 False {}
[ 0.02130931  0.39699867 -0.02959253 -0.61584127] 1.0 False {}
[ 0.02924928  0.5925213  -0.04190935 -0.91769576] 1.0 False {}
[ 0.0410997   0.39799026 -0.06026326 -0.63847315] 1.0 False {}
[ 0.04905951  0.20375808 -0.07303273 -0.3653604 ] 1.0 False {}
[ 0.05313467  0.00974588 -0.08033994 -0.09657043] 1.0 False {}
[ 0.05332959  0.20592189 -0.08227134 -0.41347983] 1.0 False {}
[ 0.05744803  0.40210778 -0.09054095 -0.7309238 ] 1.0 False {}
[ 0.06549019  0.5983566  -0.10515942 -1.050674  ] 1.0 False {}
[ 0.07745732  0.79470426 -0.1261729  -1.3744284 ] 1.0 False {}
[ 0.0933514   0.6013648  -0.15366146 -1.123721  ] 1.0 False {}
[ 0.10537869  0.40855396 -0.17613588 -0.88291144] 1.0 False {}
[ 0.11354978  0.21620502 -0.19379412 -0.65036863] 1.0 False {}
[ 0.11787388  0.41342252 -0.20680149 -0.99727666] 1.0 False {}
[ 0.12614232  0.6106189  -0.22674702 -1.3471359 ] 1.0 True {'TimeLimit.truncated': False}
[ 0.1383547   0.41894928 -0.

In [10]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense,Flatten
from keras.optimizers import Adam


In [11]:
modelq=Sequential()
modelq.add(Flatten(input_shape=(1,4)))
modelq.add(Dense(48,activation='relu'))
modelq.add(Dense(24,activation='relu'))
modelq.add(Dense(2,activation='linear'))
modelq.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 4)                 0         
                                                                 
 dense (Dense)               (None, 48)                240       
                                                                 
 dense_1 (Dense)             (None, 24)                1176      
                                                                 
 dense_2 (Dense)             (None, 2)                 50        
                                                                 
Total params: 1,466
Trainable params: 1,466
Non-trainable params: 0
_________________________________________________________________


In [12]:
from rl.agents import DQNAgent
from rl.memory import SequentialMemory
from rl.policy import BoltzmannQPolicy

ModuleNotFoundError: No module named 'rl'

In [ ]:
policy=BoltzmannQPolicy()
memory=SequentialMemory(limit=50000,window_length=1)
robot=DQNAgent(model=modelq, policy=policy,memory=memory,nb_actions=2
               ,nb_steps_warmup=10,target_model_update=1e-2)
robot.compile(Adam(lr=1e-3),metrics=['mae'])

In [ ]:
robot.fit(env=env,nb_steps=50000,visualize=False,verbose=True)


Training for 50000 steps ...
Interval 1 (0 steps performed)
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
    1/10000 [..............................] - ETA: 4:35 - reward: 1.0000

d:\sohrab\ai\rl\lib\site-packages\rl\memory.py:40: UserWarning: Not enough entries to sample without replacement. Consider increasing your warm-up phase to avoid oversampling!
  warnings.warn('Not enough entries to sample without replacement. Consider increasing your warm-up phase to avoid oversampling!')


10000/10000 [==============================] - 24s 2ms/step - reward: 1.0000
106 episodes - episode_reward: 94.264 [9.000, 221.000] - loss: 1.678 - mae: 18.584 - mean_q: 37.821

Interval 2 (10000 steps performed)
10000/10000 [==============================] - 27s 3ms/step - reward: 1.0000
62 episodes - episode_reward: 161.210 [133.000, 191.000] - loss: 2.016 - mae: 34.486 - mean_q: 69.790

Interval 3 (20000 steps performed)
10000/10000 [==============================] - 28s 3ms/step - reward: 1.0000
57 episodes - episode_reward: 175.632 [123.000, 271.000] - loss: 3.470 - mae: 34.141 - mean_q: 68.787

Interval 4 (30000 steps performed)
10000/10000 [==============================] - 42s 4ms/step - reward: 1.0000
59 episodes - episode_reward: 168.932 [144.000, 222.000] - loss: 1.760 - mae: 40.341 - mean_q: 81.655

Interval 5 (40000 steps performed)
10000/10000 [==============================] - 27s 3ms/step - reward: 1.0000
done, took 148.274 seconds


In [ ]:
out=robot.test(env,nb_episodes=10,visualize=False)

Testing for 10 episodes ...
Episode 1: reward: 500.000, steps: 500
Episode 2: reward: 500.000, steps: 500
Episode 3: reward: 500.000, steps: 500
Episode 4: reward: 500.000, steps: 500
Episode 5: reward: 500.000, steps: 500
Episode 6: reward: 500.000, steps: 500
Episode 7: reward: 500.000, steps: 500
Episode 8: reward: 500.000, steps: 500
Episode 9: reward: 500.000, steps: 500
Episode 10: reward: 500.000, steps: 500


In [ ]:
robot.save_weights('rl.h5')